### Register a new user
POST {{host}}/api/users/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456",
  "email": "newuser@example.com",
  "firstName": "New",
  "lastName": "User",
  "phoneNumber": "1234567890",
  "role": "CUSTOMER"
}

### Login user
POST {{host}}/api/users/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}

### Login organizer
POST {{host}}/api/users/login
Content-Type: application/json

{
  "username": "organizer",
  "password": "123456"
}

### Get user profile
GET {{host}}/api/users/profile
Authorization: Bearer {{authToken}}
